#!/usr/bin/env python3

import json, os
from datetime import datetime
from urllib.parse import urlencode
from urllib.request import Request, urlopen

query = """
{
  issues: search(type: ISSUE, query: "author:figsoda is:issue") {
    issueCount
  }

  prs: search(type: ISSUE, query: "author:figsoda is:pr") {
    issueCount
  }

  user(login: "figsoda") {
    followers { totalCount }
    gists { totalCount }
    issues { totalCount }
    name
    pullRequests { totalCount }
    repositories(first: 100, isFork: false, privacy: PUBLIC) {
      totalCount
      nodes {
        forkCount
        languages(first: 100) {
          edges {
            node { name }
            size
          }
        }
        stargazerCount
      }
    }
    repositoriesContributedTo(privacy: PUBLIC) {
      totalCount
    }
    url
  }
}
"""

commits = json.load(urlopen(Request(
    "https://api.github.com/search/commits?q=author:figsoda&per_page=1",
    headers = {"Accept": "application/vnd.github.cloak-preview"},
)))["total_count"]

data = json.load(urlopen(Request(
    "https://api.github.com/graphql",
    json.dumps({"query": query}).encode("ascii"),
    {"Authorization": f"token {os.getenv('TOKEN')}"},
)))["data"]
user = data["user"]

forks = 0
langs = {}
size = 0
stars = 0

for repo in user["repositories"]["nodes"]:
    forks += repo["forkCount"]
    stars += repo["stargazerCount"]
    for lang in repo["languages"]["edges"]:
        size += lang["size"]
        name = lang["node"]["name"]
        langs[name] = langs.get(name, 0) + lang["size"]

readme = open("README.md", "w")

readme.write(f"""
# [{user["name"]}]({user["url"]})


## Statistics

<table>
  <tr>
    <td>Repositories</td>
    <td><a href="https://github.com/figsoda?tab=repositories">
      {user["repositories"]["totalCount"]}
    </a></td>
  </tr>
  <tr>
    <td>Gists</td>
    <td><a href="https://gist.github.com/figsoda">
      {user["gists"]["totalCount"]}
    </a></td>
  </tr>
  <tr>
    <td>Stargazers</td>
    <td>{stars}</td>
  </tr>
  <tr>
    <td>Forks</td>
    <td>{forks}</td>
  </tr>
  <tr>
    <td>Contributed to</td>
    <td>{user["repositoriesContributedTo"]["totalCount"]}</td>
  </tr>
  <tr>
    <td>Commits</td>
    <td>{commits}</td>
  </tr>
  <tr>
    <td>Issues</td>
    <td>{data["issues"]["issueCount"]}</td>
  </tr>
  <tr>
    <td>Pull requests</td>
    <td>{data["prs"]["issueCount"]}</td>
  </tr>
  <tr>
    <td>Followers</td>
    <td><a href="https://github.com/figsoda?tab=followers">
      {user["followers"]["totalCount"]}
    </a></td>
  </tr>
</table>


## Most used languages

<table>
""")

for k, v in sorted(langs.items(), key = lambda x: x[1], reverse = True):
    readme.write(f"<tr><td>{k}</td><td>{round(v / size * 100, 2)}%</td></tr>")

readme.write(f"""
</table>


<sub>Last updated: {datetime.now().strftime("%F %T")}</sub>
""")
